#!/usr/bin/env bash
# Shared runtime path defaults for harness and OpenCode server processes.

WORKSPACE_DIR=${WORKSPACE_DIR:-/workspace}
HARNESS_STATE_DIR=${HARNESS_STATE_DIR:-/harness-state}
INSTRUCTIONS_FILE=${INSTRUCTIONS_FILE:-$HARNESS_STATE_DIR/instructions.txt}
FORK_CONTEXT_FILE=${FORK_CONTEXT_FILE:-$HARNESS_STATE_DIR/fork-context.md}
EXTRA_RUN_INSTRUCTIONS_FILE=${EXTRA_RUN_INSTRUCTIONS_FILE:-$HARNESS_STATE_DIR/extra-run-instructions.md}
SETUP_LOG=${SETUP_LOG:-$HARNESS_STATE_DIR/setup.log}
CLIENT_LOG=${OPENCODE_CLIENT_LOG:-$HARNESS_STATE_DIR/opencode-client.log}
HARNESS_STATUS_FILE=${HARNESS_STATUS_FILE:-$HARNESS_STATE_DIR/harness-status.txt}
REBASE_CONTINUE_CHECK_FILE=${REBASE_CONTINUE_CHECK_FILE:-$HARNESS_STATE_DIR/rebase-continue-check.sh}
REBASE_SKIPPED_COMMITS_FILE=${REBASE_SKIPPED_COMMITS_FILE:-$HARNESS_STATE_DIR/rebase-skipped-commits.json}
REBASE_CONFLICTING_COMMITS_FILE=${REBASE_CONFLICTING_COMMITS_FILE:-$HARNESS_STATE_DIR/rebase-conflicting-commits.json}
FORKLIFT_REBASE_EVENTS_SOCK=${FORKLIFT_REBASE_EVENTS_SOCK:-}

export WORKSPACE_DIR HARNESS_STATE_DIR INSTRUCTIONS_FILE FORK_CONTEXT_FILE EXTRA_RUN_INSTRUCTIONS_FILE SETUP_LOG CLIENT_LOG HARNESS_STATUS_FILE
export REBASE_CONTINUE_CHECK_FILE REBASE_SKIPPED_COMMITS_FILE REBASE_CONFLICTING_COMMITS_FILE
export FORKLIFT_REBASE_EVENTS_SOCK
