#!/usr/bin/env bash
# Shared runtime path defaults for harness and OpenCode server processes.

WORKSPACE_DIR=${WORKSPACE_DIR:-/workspace}
HARNESS_STATE_DIR=${HARNESS_STATE_DIR:-/harness-state}
INSTRUCTIONS_FILE=${INSTRUCTIONS_FILE:-$HARNESS_STATE_DIR/instructions.txt}
FORK_CONTEXT_FILE=${FORK_CONTEXT_FILE:-$HARNESS_STATE_DIR/fork-context.md}
EXTRA_RUN_INSTRUCTIONS_FILE=${EXTRA_RUN_INSTRUCTIONS_FILE:-$HARNESS_STATE_DIR/extra-run-instructions.md}
SETUP_LOG=${SETUP_LOG:-$HARNESS_STATE_DIR/setup.log}
CLIENT_LOG=${OPENCODE_CLIENT_LOG:-$HARNESS_STATE_DIR/opencode-client.log}
HARNESS_STATUS_FILE=${HARNESS_STATUS_FILE:-$HARNESS_STATE_DIR/harness-status.txt}
REBASE_CONTINUE_CHECK_FILE=${REBASE_CONTINUE_CHECK_FILE:-$HARNESS_STATE_DIR/rebase-continue-check.sh}
REBASE_REPORT_FILE=${REBASE_REPORT_FILE:-$HARNESS_STATE_DIR/rebase-report.json}
FORKLIFT_REBASE_EVENTS_SOCK=${FORKLIFT_REBASE_EVENTS_SOCK:-}
FORKLIFT_REBASE_CONTROL_SOCK=${FORKLIFT_REBASE_CONTROL_SOCK:-/run/forklift/rebase-control.sock}
FORKLIFT_AGENT_LIFETIME=${FORKLIFT_AGENT_LIFETIME:-conflict}

FORKLIFT_TOOLCHAIN_PATH=/opt/pyenv/shims:/opt/pyenv/bin:/opt/n/bin:/opt/bun/bin:/opt/cargo/bin:/opt/opencode/bin
PATH="$FORKLIFT_TOOLCHAIN_PATH:$PATH"

export WORKSPACE_DIR HARNESS_STATE_DIR INSTRUCTIONS_FILE FORK_CONTEXT_FILE EXTRA_RUN_INSTRUCTIONS_FILE SETUP_LOG CLIENT_LOG HARNESS_STATUS_FILE
export REBASE_CONTINUE_CHECK_FILE REBASE_REPORT_FILE
export FORKLIFT_REBASE_EVENTS_SOCK FORKLIFT_REBASE_CONTROL_SOCK FORKLIFT_AGENT_LIFETIME PATH
